### ISSUE TITLE
[BUG]yurt-tunnel-server panic while nat chain OUTPUT not jumps to TUNNEL-PORT

### ISSUE THREAD

**Issue by zf930530** [openyurtio/openyurt#1096]
**What happened**:
yurt-tunnel-server pod crashed with log:
I1209 02:51:13.119639       1 start.go:54] yurttunnel-server version: projectinfo.Info{GitVersion:"latest", GitCommit:"ef26d5c", BuildDate:"2021-12-03T07:50:34Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
W1209 02:51:13.119881       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I1209 02:51:13.122440       1 options.go:155] yurttunnel server config: &config.Config{EgressSelectorEnabled:false, EnableIptables:true, EnableDNSController:true, IptablesSyncPeriod:60, DNSSyncPeriod:1800, CertDNSNames:[]string{}, CertIPs:[]net.IP{}, ListenAddrForAgent:"192.168.0.6:10262", ListenAddrForMaster:"192.168.0.6:10263", ListenInsecureAddrForMaster:"192.168.0.6:10264", ListenMetaAddr:"192.168.0.6:10265", RootCert:(*x509.CertPool)(0xc00038e2a0), Client:(*kubernetes.Clientset)(0xc00027b4a0), SharedInformerFactory:(*informers.sharedInformerFactory)(0xc0002701e0), ServerCount:1, ProxyStrategy:"destHost", InterceptorServerUDSFile:""}
I1209 02:51:13.122990       1 leaderelection.go:242] attempting to acquire leader lease  kube-system/tunnel-dns-controller...
E1209 02:51:13.131413       1 iptables.go:200] failed to delete rule that nat chain OUTPUT jumps to TUNNEL-PORT: error checking rule: exit status 2: iptables v1.6.0: Couldn't load target `TUNNEL-PORT':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
E1209 02:51:18.143436       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 1 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x15d4920, 0x22eb0e0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.9-rc.0/pkg/util/runtime/runtime.go:74 +0xa6
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.9-rc.0/pkg/util/runtime/runtime.go:48 +0x89
panic(0x15d4920, 0x22eb0e0)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/openyurtio/openyurt/pkg/yurttunnel/server/serveraddr.NodeListToNodes(0x0, 0xc00027b4a0, 0xc000430900, 0xc000443040)
	/opt/src/pkg/yurttunnel/server/serveraddr/addr.go:355 +0x72
github.com/openyurtio/openyurt/pkg/yurttunnel/server/serveraddr.GetYurttunelServerDNSandIP(0x19ce420, 0xc00027b4a0, 0xc0000f56f0, 0x2, 0x2, 0xc0000f56e4, 0x2, 0x2, 0x17f5124ef9108, 0x0)
	/opt/src/pkg/yurttunnel/server/serveraddr/addr.go:109 +0xd2
github.com/openyurtio/openyurt/pkg/yurttunnel/pki/certmanager.NewYurttunnelServerCertManager.func1(0xc0000f5718, 0xc00008a6c0, 0x12a05f200)
	/opt/src/pkg/yurttunnel/pki/certmanager/certmanager.go:61 +0x76
k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection(0xc0000f5930, 0xc0000f5600, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.9-rc.0/pkg/util/wait/wait.go:211 +0x69
k8s.io/apimachinery/pkg/util/wait.WaitFor(0xc0002135a0, 0xc0000f5930, 0xc00008a600, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.9-rc.0/pkg/util/wait/wait.go:541 +0x145
k8s.io/apimachinery/pkg/util/wait.PollUntil(0x12a05f200, 0xc0000f5930, 0xc00008a720, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.9-rc.0/pkg/util/wait/wait.go:492 +0xc5
github.com/openyurtio/openyurt/pkg/yurttunnel/pki/certmanager.NewYurttunnelServerCertManager(0x19ce420, 0xc00027b4a0, 0x19cb3a0, 0xc0002701e0, 0x233e198, 0x0, 0x0, 0x233e198, 0x0, 0x0, ...)
	/opt/src/pkg/yurttunnel/pki/certmanager/certmanager.go:60 +0x10f
github.com/openyurtio/openyurt/cmd/yurt-tunnel-server/app.Run(0xc0000f5c10, 0xc00008a720, 0x0, 0x0)
	/opt/src/cmd/yurt-tunnel-server/app/start.go:110 +0x125
github.com/openyurtio/openyurt/cmd/yurt-tunnel-server/app.NewYurttunnelServerCommand.func1(0xc00030b080, 0xc00037e540, 0x0, 0x6, 0x0, 0x0)
	/opt/src/cmd/yurt-tunnel-server/app/start.go:64 +0x2c7
github.com/spf13/cobra.(*Command).execute(0xc00030b080, 0xc0000b0010, 0x6, 0x6, 0xc00030b080, 0xc0000b0010)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc00030b080, 0xc000086180, 0xc000401020, 0xc00008a720)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/opt/src/cmd/yurt-tunnel-server/server.go:49 +0x21e
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x1458eb2]

goroutine 1 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.9-rc.0/pkg/util/runtime/runtime.go:55 +0x10c
panic(0x15d4920, 0x22eb0e0)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/openyurtio/openyurt/pkg/yurttunnel/server/serveraddr.NodeListToNodes(0x0, 0xc00027b4a0, 0xc000430900, 0xc000443040)
	/opt/src/pkg/yurttunnel/server/serveraddr/addr.go:355 +0x72
github.com/openyurtio/openyurt/pkg/yurttunnel/server/serveraddr.GetYurttunelServerDNSandIP(0x19ce420, 0xc00027b4a0, 0xc0000f56f0, 0x2, 0x2, 0xc0000f56e4, 0x2, 0x2, 0x17f5124ef9108, 0x0)
	/opt/src/pkg/yurttunnel/server/serveraddr/addr.go:109 +0xd2
github.com/openyurtio/openyurt/pkg/yurttunnel/pki/certmanager.NewYurttunnelServerCertManager.func1(0xc0000f5718, 0xc00008a6c0, 0x12a05f200)
	/opt/src/pkg/yurttunnel/pki/certmanager/certmanager.go:61 +0x76
k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection(0xc0000f5930, 0xc0000f5600, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.9-rc.0/pkg/util/wait/wait.go:211 +0x69
k8s.io/apimachinery/pkg/util/wait.WaitFor(0xc0002135a0, 0xc0000f5930, 0xc00008a600, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.9-rc.0/pkg/util/wait/wait.go:541 +0x145
k8s.io/apimachinery/pkg/util/wait.PollUntil(0x12a05f200, 0xc0000f5930, 0xc00008a720, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.9-rc.0/pkg/util/wait/wait.go:492 +0xc5
github.com/openyurtio/openyurt/pkg/yurttunnel/pki/certmanager.NewYurttunnelServerCertManager(0x19ce420, 0xc00027b4a0, 0x19cb3a0, 0xc0002701e0, 0x233e198, 0x0, 0x0, 0x233e198, 0x0, 0x0, ...)
	/opt/src/pkg/yurttunnel/pki/certmanager/certmanager.go:60 +0x10f
github.com/openyurtio/openyurt/cmd/yurt-tunnel-server/app.Run(0xc0000f5c10, 0xc00008a720, 0x0, 0x0)
	/opt/src/cmd/yurt-tunnel-server/app/start.go:110 +0x125
github.com/openyurtio/openyurt/cmd/yurt-tunnel-server/app.NewYurttunnelServerCommand.func1(0xc00030b080, 0xc00037e540, 0x0, 0x6, 0x0, 0x0)
	/opt/src/cmd/yurt-tunnel-server/app/start.go:64 +0x2c7
github.com/spf13/cobra.(*Command).execute(0xc00030b080, 0xc0000b0010, 0x6, 0x6, 0xc00030b080, 0xc0000b0010)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc00030b080, 0xc000086180, 0xc000401020, 0xc00008a720)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/opt/src/cmd/yurt-tunnel-server/server.go:49 +0x21e

**What you expected to happen**:
yurt-tunnel-server can run normally.

**How to reproduce it (as minimally and precisely as possible)**:
Tunnel-server crashes when the output chain does not contain the TUNNEL-PORT target.
$ iptables -t nat -nvL
Chain OUTPUT (policy ACCEPT 108 packets, 5937 bytes)
 pkts bytes target     prot opt in     out     source               destination         
 308K   17M KUBE-SERVICES  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kubernetes service portals */
 212K   11M DOCKER     all  --  *      *       0.0.0.0/0           !127.0.0.0/8          ADDRTYPE match dst-type LOCAL

**Anything else we need to know?**:

**Environment**:
- OpenYurt version:v1.1.0
- Kubernetes version (use `kubectl version`):v1.20.10
- OS (e.g: `cat /etc/os-release`):Centos 7
- Kernel (e.g. `uname -a`):3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:https://openyurt.io/zh/docs/installation/manually-setup
- Others:

**others**

/kind bug

**Comment by zf930530** [comment]
https://github.com/openyurtio/openyurt-helm
Found that deployment deployed by helm with latest is old version,I change the tag to v1.1.0 and tunnel-server pod back to normal.Thx
