### ISSUE TITLE
[BUG] yurt-controller-manager fails on start when using tag `latest`

### ISSUE THREAD

**Issue by batthebee** [openyurtio/openyurt#1171]
**What happened**:

After installing openyurt v1.1 with image tags latest, yurt-controller-manager fails because of insufficient rights.

Following the manual setup, I'm installing the helm chart from git tag `v1.1.0` with the following values:

```yaml
    values:
      yurtTunnelServer:
        image:
          tag: latest
      yurtTunnelAgent:
        image:
          tag: latest
      yurtControllerManager:
        image:
          tag: latest
```

This results in: 

```bash
k logs -n kube-system yurt-controller-manager-7dfdf68d47-5pzbc -f
W0125 14:04:22.215944       1 client_config.go:615] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0125 14:04:22.219919       1 leaderelection.go:248] attempting to acquire leader lease kube-system/yurt-controller-manager...
yurtcontroller-manager version: projectinfo.Info{GitVersion:"-5f7f1a2", GitCommit:"5f7f1a2", BuildDate:"2023-01-25T02:05:25Z", GoVersion:"go1.17.1", Compiler:"gc", Platform:"linux/amd64", AllVersions:[]string{""}}
I0125 14:04:38.267695       1 leaderelection.go:258] successfully acquired lease kube-system/yurt-controller-manager
I0125 14:04:38.268072       1 event.go:282] Event(v1.ObjectReference{Kind:"Lease", Namespace:"kube-system", Name:"yurt-controller-manager", UID:"b857c7e8-48ea-4466-8a73-1215cc6861c2", APIVersion:"coordination.k8s.io/v1", ResourceVersion:"14667", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' kubeadm-openyurt-w2_0aa62f2d-0f24-401b-88b1-b144b3e4cb3c became leader
I0125 14:04:38.278406       1 controllermanager.go:373] Started "daemonpodupdater"
I0125 14:04:38.278463       1 daemon_pod_updater_controller.go:215] Starting daemonPodUpdater controller
I0125 14:04:38.282986       1 servicetopology.go:297] v1.EndpointSlice is supported.
I0125 14:04:38.283071       1 controllermanager.go:373] Started "servicetopologycontroller"
I0125 14:04:38.283172       1 servicetopology.go:93] starting the service topology controller
I0125 14:04:38.284522       1 controllermanager.go:373] Started "webhookmanager"
I0125 14:04:38.287930       1 controllermanager.go:373] Started "poolcoordinatorcertmanager"
I0125 14:04:38.288096       1 poolcoordinator_cert_manager.go:219] Starting poolcoordinatorCertManager controller
I0125 14:04:38.291367       1 poolcoordinator_cert_manager.go:367] fail to get CA from secret: secrets "pool-coordinator-ca-certs" is forbidden: User "system:serviceaccount:kube-system:yurt-controller-manager" cannot get resource "secrets" in API group "" in the namespace "kube-system", create new CA
I0125 14:04:38.305740       1 controllermanager.go:373] Started "poolcoordinator"
I0125 14:04:38.315573       1 csrapprover.go:125] v1.CertificateSigningRequest is supported.
I0125 14:04:38.315689       1 controllermanager.go:373] Started "yurtcsrapprover"
I0125 14:04:38.326291       1 csrapprover.go:185] starting the crsapprover
I0125 14:04:38.386059       1 servicetopology.go:99] sync service topology controller succeed
I0125 14:04:38.426160       1 poolcoordinator_controller.go:227] start node taint workers
E0125 14:04:38.506594       1 poolcoordinator_cert_manager.go:226] fail to init poolcoordinator init poolcoordinator failed: fail to write CA assets into secret when initializing poolcoordinator: create secret client pool-coordinator-ca-certs fail: secrets is forbidden: User "system:serviceaccount:kube-system:yurt-controller-manager" cannot create resource "secrets" in API group "" in the namespace "kube-system"
I0125 14:04:38.547340       1 webhook.go:99] tls key and cert ok.
I0125 14:04:38.547378       1 poolcoordinator_webhook.go:659] populate nodepool map
I0125 14:04:38.547421       1 poolcoordinator_webhook.go:666] start nodepool maintenance worker
F0125 14:04:38.551466       1 poolcoordinator_webhook.go:595] failed to get validatewebhookconfiguration yurt-controller-manager, validatingwebhookconfigurations.admissionregistration.k8s.io "yurt-controller-manager" is forbidden: User "system:serviceaccount:kube-system:yurt-controller-manager" cannot get resource "validatingwebhookconfigurations" in API group "admissionregistration.k8s.io" at the cluster scope
goroutine 151 [running]:
k8s.io/klog/v2.stacks(0x1)
	/go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:1026 +0x8a
k8s.io/klog/v2.(*loggingT).output(0x2d2aae0, 0x3, {0x0, 0x0}, 0xc0003ba230, 0x0, {0x22d4e3f, 0xc00092a1e0}, 0x0, 0x0)
	/go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:975 +0x63d
k8s.io/klog/v2.(*loggingT).printf(0x0, 0x0, {0x0, 0x0}, {0x0, 0x0}, {0x1bdd972, 0x31}, {0xc00092a1e0, 0x2, ...})
	/go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:753 +0x1e5
k8s.io/klog/v2.Fatalf(...)
	/go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:1514
github.com/openyurtio/openyurt/pkg/webhook.(*PoolCoordinatorWebhook).ensureValidatingConfiguration(0xc0007aac00, 0xc0003b2bd0)
```

I think, the `yurt-controller-manager` cluster role need's the following additional rights: 

```yaml
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
  - patch
  - create
  - delete
  - update

```

**Environment**:
- OpenYurt version: v1.1.0
- Kubernetes version (use `kubectl version`): v1.22.17
- OS (e.g: `cat /etc/os-release`): ubuntu 20.04
- Kernel (e.g. `uname -a`): 5.15.0-58-generic
- Install tools: manual/ansible

/kind bug

**Comment by batthebee** [comment]
Using master branch instead of v1.1.0 fixes the problem. Maybe it make sense to change docs!?
